apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: calculator-addition-test
  namespace: testkube
spec:
  content:
    git:
      url: https://github.com/techmaharaj/calculator-service.git
      branch: olensmar/demo
      files:
      - path: tests/calculator-addition.postman_collection.json
  container:
    resources:
      requests:
        cpu: 256m
        memory: 128Mi
    workingDir: /data/repo
  steps:
    - name: Run Calculator Addition Tests
      run:
        image: postman/newman:5-alpine
        args:
          - run
          - calculator-addition.postman_collection.json
          - --reporters
          - cli,json
          - --reporter-json-export
          - test-results.json
          - --verbose